routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/domains/addverification/{domain}', 'DomainController@addVerification')->name('domains.addverification');

Route::get('/domains/checkverification/{verification}', 'DomainController@checkVerification')->name('domains.checkverification');

Route::resource('domains', 'DomainController');

app/Domain.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    protected $fillable = [
        'user_id',
        'name'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function verifications()
    {
        return $this->hasMany('App\DomainVerification');
    }

    public function hasAtLeastOneVerification()
    {
        foreach ($this->verifications as $verification) {
            if ($verification->isVerified())
                return true;
        }
        return false;
    }
}

app/DomainVerification.php
<?php

namespace App;

use App\DomainVerification\Factory as DomainVerificationFactory;
use App\DomainVerification\Status;
use Illuminate\Database\Eloquent\Model;

class DomainVerification extends Model
{
    protected $table = 'domain_verifications';

    protected $fillable = [
        'domain_id',
        'type',
        'token',
        'status',
        'last_verified'
    ];

    public function domain()
    {
        return $this->belongsTo('App\Domain');
    }

    public function isVerified() : bool
    {
        return ($this->status == Status::VERIFIED);
    }

    public function newFromBuilder($attributes = [], $connection = null)
    {
        $model = DomainVerificationFactory::getInstanceByType($attributes->type);

        $model->exists = true;
        $model->setRawAttributes((array) $attributes, true);
        $model->setConnection($connection ?: $this->getConnectionName());
        $model->fireModelEvent('retrieved', false);

        return $model;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function domains()
    {
        return $this->hasMany('App\Domain');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DomainController.php
<?php

namespace App\Http\Controllers;

use App\Domain;
use App\DomainVerification;
use App\DomainVerification\Factory as DomainVerificationFactory;
use App\DomainVerification\Types as DomainVerificationTypes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Validator;

class DomainController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $domains = Auth::user()->domains()->simplePaginate(5);
        return view('domain.list')->with('domains', $domains);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('domain.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => [
                'required',
                'string',
                'max:255',
                'regex:/^[a-zA-Z0-9]+([a-zA-Z0-9\-]{0,2}[a-zA-Z0-9]+|[a-zA-Z0-9]*)*\.[a-zA-Z]{2,}$/i'
            ],
        ]);
        $validator->validate();

        $name = $request->get('name');
        $name = strtolower($name);

        $duplicate_domain = Auth::user()->domains()->where(['name' => $name])->get();
        if ( !$duplicate_domain->isEmpty() ) {
            return back()->withErrors(['duplicate' => 'Already added this domain!']);
        }

        Domain::create([
            'name' => $name,
            'user_id' => Auth::user()->id
        ]);

        return redirect()->route('domains.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function show(Domain $domain)
    {
        Gate::authorize('domain', $domain);

        return view('domain.show')->with('domain', $domain);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function edit(Domain $domain)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Domain $domain)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function destroy(Domain $domain)
    {
        //
    }

    public function addVerification(Domain $domain)
    {
        Gate::authorize('domain', $domain);

        $duplicate_verification = $domain->verifications()->where(['type' => DomainVerificationTypes::DNS])->get();
        if ( !$duplicate_verification->isEmpty() ) {
            return back()->withErrors(['duplicate' => 'Already added verification!']);
        }

        $new_domain_verification = DomainVerificationFactory::getInstanceByType(DomainVerificationTypes::DNS);
        $new_domain_verification->generate($domain);

        return redirect()->route('domains.show', [$domain]);
    }

    public function checkVerification(DomainVerification $verification)
    {
        Gate::authorize('domain', $verification->domain);

        $verification->check();

        return redirect()->route('domains.show', [$verification->domain]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/domain/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create new Domain') }}</div>

                    <div class="card-body">
                        @error('duplicate')
                        <div class="alert alert-warning" role="alert">
                            {{ $errors->first('duplicate') }}
                        </div>
                        @enderror

                        <form method="POST" action="{{ route('domains.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Add Domain') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/domain/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Domains</div>

                    <div class="card-body">
                        <a href="{{ route('domains.create') }}">
                            <button type="button" class="btn btn-primary">Add Domain</button>
                        </a>
                        <br/>
                        <br/>
                        <div class="list-group">
                            @if ($domains->count() < 1)
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">You dont have any domains! :(</h5>
                                </div>
                            @else
                                @foreach ($domains as $domain)
                                    <a href="{{ route('domains.show', $domain->id) }}" class="list-group-item list-group-item-action flex-column align-items-start ">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="mb-1">{{ $domain->name }}</h5>
                                            <small>{{ $domain->created_at->diffForHumans() }}</small>
                                        </div>
                                        @if ($domain->hasAtLeastOneVerification())
                                            <span class="badge badge-success">Verified</span>
                                        @else
                                            <span class="badge badge-warning">Not Verified</span>
                                        @endif
                                    </a>
                                @endforeach
                                {{ $domains->links() }}
                            @endif

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/domain/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Domain Details') }}</div>

                    <div class="card-body">
                        @error('duplicate')
                        <div class="alert alert-warning" role="alert">
                            {{ $errors->first('duplicate') }}
                        </div>
                        @enderror
                        <div class="list-group">
                            <div class="list-group-item list-group-item-action flex-column align-items-start ">
                                <div class="d-flex w-100">
                                    <small>Name</small>
                                </div>
                                <h5 class="mb-1">{{ $domain->name }}</h5>
                            </div>

                            @if ($domain->verifications->count() > 0)
                                @foreach ($domain->verifications as $verification)
                                    <div class="list-group-item list-group-item-action flex-column align-items-start ">
                                        <div class="d-flex w-100">
                                            <small>Verification Type</small>
                                        </div>
                                        <h5 class="mb-1">{{ config('enums.domain_verification_types')[$verification->type] }}</h5>

                                        <div class="d-flex w-100">
                                            <small>Token</small>
                                        </div>
                                        <h5 class="mb-1">{{ $verification->token }}</h5>

                                        <div class="d-flex w-100">
                                            <small>Status</small>
                                        </div>

                                        @if ($verification->status == 1)
                                            <span class="badge badge-success">Verified</span>
                                        @else
                                            <span class="badge badge-warning">Not Verified</span>
                                        @endif

                                        <a href="{{ route('domains.checkverification', $verification->id) }}">
                                            <button type="button" class="btn btn-primary">Refresh</button>
                                        </a>
                                    </div>
                                @endforeach
                            @else
                                <div class="list-group-item list-group-item-action flex-column align-items-start ">
                                    <span class="badge badge-warning">Not Verified</span>
                                </div>
                            @endif
                        </div>
                        <br/>
                        <a href="{{ route('domains.addverification', $domain->id) }}">
                            <button type="button" class="btn btn-primary">Add Verification</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!

                    <hr/>
                        <a href="/domains">
                            <button type="button" class="btn btn-dark">My Domains</button>
                        </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>